version: "3.7"

services:
  app:
    container_name: console_app
    build: docker/php
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2-starter-kit
      MYSQL_USER: ysk_dbu
      MYSQL_PASSWORD: ysk_pass